### ISSUE TITLE
5.4 normalization issue

### ISSUE THREAD

**Issue by DLumi** [fchollet/deep-learning-with-python-notebooks#156]
I really hate this whole book being so outdated, but still.
Does anyone know what should I do with gradient tensor normalization?
The code in the book (and in the notebook here) goes as follows:
`grads /= (K.sqrt(K.mean(K.square(grads))) + 1e-5)`

and once I copy it into my notebook I get this:

`ValueError: Tensor("Const_2:0", shape=(4,), dtype=int32) must be from the same graph as Tensor("Square_2:0", shape=(None, None, None, 3), dtype=float32) (graphs are <tensorflow.python.framework.ops.Graph object at 0x7f3a0d868550> and FuncGraph(name=keras_graph, id=139887061480000)).`

Google doesn't really have anything useful to offer.

**Comment by piscestan** [comment]
我也遇到了同样的问题，但问题的关键不在于调整import，在jupyter-notebook中将原始代码运行两次，就不再报这样的错误，虽然我也不知道为什么会这样。
I also encountered the same problem, but the key to the problem is not to adjust the import. After running the original code twice in jupyter-notebook, it no longer reports such an error, although I don’t know why this happens.
